# This workflow builds the Python project into cross-platform executables using PyInstaller.
# The version is set based on the branch name.

name: Build Cross-Platform Executable

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Get version from branch
        id: get_version
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          # Remove slashes and illegal chars, fallback to 'dev' if not found
          VERSION=$(echo "$BRANCH_NAME" | sed 's#[^a-zA-Z0-9._-]#-#g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py --name "KingGodCastleAIO-${{ steps.get_version.outputs.version }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KingGodCastleAIO-${{ matrix.os }}-${{ steps.get_version.outputs.version }}
          path: dist/*
